
replicaCount: 2

langfuse:
  port: 3000
  nodeEnv: production
  nextauth:
    url: http://k8s-default-langfuse-0f53f86de0-1897863856.ap-southeast-1.elb.amazonaws.com:3000
  telemetryEnabled: True
  nextPublicSignUpDisabled: False
  enableExperimentalFeatures: False
  extraContainers: []
  extraVolumes: []
  extraInitContainers: []
  extraVolumeMounts: []
  additionalEnv:
    - name: DATABASE_URL
      value: "postgresql://postgres:awsAWS09100910!@dify-db.cluster-cfl91iadc31f.ap-southeast-1.rds.amazonaws.com:5432/postgres"
    - name: NEXTAUTH_SECRET
      value: "kblJ7byugOAcW9gxLg7pY6lRcOFAYfHKoztLRPCRPMY="
    - name: SALT
      value: "nlpQUZUZ7PQ1VehKCqwEgrIilNdYbkWtg7WllRoqwlE="
    - name: LANGFUSE_LOG_LEVEL
      value: info
    - name: LANGFUSE_LOG_FORMAT
      value: json

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"  # 或 "internal"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  hosts:
    - host: k8s-default-langfuse-0f53f86de0-1897863856.ap-southeast-1.elb.amazonaws.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: langfuse
              port:
                number: 3000

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  deploy: false

extraManifests: []
