apiVersion: v2
name: dify
description: Dify is an LLM application development platform. This Helm chart enables easy deployment of Dify on Kubernetes. The optimized chart size ensures faster deployment.

home: https://github.com/langgenius/dify

maintainers:
  - name: douban
  
keywords:
  - dify
  - llm
  - ai
  
annotations:
  artifacthub.io/changes: |
    - Optimized chart size by removing unnecessary blank lines
    - Set Redis and PostgreSQL as external dependencies
    - Fixed "Request entity too large" error
    - Removed embedded dependencies to reduce chart size
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: Apache-2.0

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

# Dependencies definition following the official Helm dependency mechanism
dependencies:
  - name: redis
    version: "~17.11.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.embedded
  - name: postgresql
    version: "~12.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.embedded
  - name: minio
    version: "~12.6.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.embedded
