name: Release Charts

on:
  push:
    branches:
      - main

# 这里添加权限设置以允许GitHub Actions写入仓库
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        
      # Add step to update dependencies before packaging
      - name: Update Helm dependencies
        run: helm dependency update .

      - name: Package Helm Chart
        run: |
          helm package .
          
      - name: Update index.yaml
        run: |
          helm repo index --url https://kevinzhao.github.io/dify_helm .
      
      - name: Create deployment folder
        run: |
          mkdir -p deployment
          cp index.yaml deployment/
          cp dify-*.tgz deployment/
          # 复制依赖的chart包
          mkdir -p deployment/charts
          cp charts/*.tgz deployment/charts/ || true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deployment
          branch: gh-pages
          clean: true
